In [1]:
import parserM4
import pandas as pd
import imp
import numpy as np

In [2]:
Info = parserM4.parse_bitinfocharts()

In [3]:
imp.reload(parserM4)
Bitcoin = parserM4.parse_btc()
Bitcoin['datetime'] = pd.to_datetime(Bitcoin['Time'], format='%Y-%m-%d %H:%M:%S')
Bitcoin.head()

,Height,Tx Count,Stripped Size(B),Size(B),Weight,Avg Fee Per Tx,Reward,Time,RewardFee,datetime
0,497373.0,2272.0,985361.0,1036947.0,3993030.0,0.000493,12.5 + 1.96742306 BTC,2017-12-03 14:44:19,1.967423,2017-12-03 14:44:19
1,497372.0,819.0,988514.0,1027166.0,3992708.0,0.000233,12.5 + 0.93181476 BTC,2017-12-03 14:14:04,0.931815,2017-12-03 14:14:04
2,497371.0,1035.0,966408.0,1093630.0,3992854.0,0.000080,12.5 + 0.32047298 BTC,2017-12-03 14:11:24,0.320473,2017-12-03 14:11:24
3,497370.0,2068.0,978241.0,1058253.0,3992976.0,0.000480,12.5 + 1.91764136 BTC,2017-12-03 14:10:16,1.917641,2017-12-03 14:10:16
4,497369.0,1517.0,981914.0,1046836.0,3992578.0,0.000187,12.5 + 0.74517181 BTC,2017-12-03 13:57:25,0.745172,2017-12-03 13:57:25

In [ ]:
imp.reload(parserM4)
Ethereum = parserM4.parse_ether(100)
Ethereum.head()

In [5]:
imp.reload(parserM4)
Litecoin = parserM4.parse_blockcypher('ltc')
Litecoin.head()

Error after block number 1324200 (133 blocks done)

,block_number,blockchain,fees_satoshi,nonce,time,transactions,datetime,time_block
0,1324333,LTC.main,25313206,0,2017-12-03T13:56:52Z,156,2017-12-03 13:56:52,00:04:45
1,1324332,LTC.main,14594792,0,2017-12-03T13:52:07Z,105,2017-12-03 13:52:07,00:03:26
2,1324331,LTC.main,8434928,0,2017-12-03T13:48:41Z,46,2017-12-03 13:48:41,00:01:09
3,1324330,LTC.main,4701548,0,2017-12-03T13:47:32Z,38,2017-12-03 13:47:32,00:00:51
4,1324329,LTC.main,3101072,0,2017-12-03T13:46:41Z,25,2017-12-03 13:46:41,00:00:20

In [6]:
imp.reload(parserM4)
Dash = parserM4.parse_blockcypher('dash')
Dash.head()

Error after block number 781032 (3 blocks done)

,block_number,blockchain,fees_satoshi,nonce,time,transactions,datetime,time_block
0,781035,DASH.main,2232843,0,2017-12-03T14:02:59Z,29,2017-12-03 14:02:59,00:04:47
1,781034,DASH.main,244872,0,2017-12-03T13:58:12Z,9,2017-12-03 13:58:12,00:01:15
2,781033,DASH.main,675587,0,2017-12-03T13:56:57Z,26,2017-12-03 13:56:57,NaT

In [7]:
imp.reload(parserM4)
Dogecoin = parserM4.parse_blockcypher('doge')
Dogecoin.head()

Too many requests

TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

In [9]:
Model = pd.DataFrame()
Model[''] = ['Avg Nb transac','Avg fee per transaction','Avg reward fee per bloc',
                       'Avg Waiting time between two blocs','St dev nb transac','St dev fee per bloc',
                       'St dev fee per transaction','St dev waiting time between 2 blocs',
                       'Percentile 5% nb transac','Percentile 95% fee per bloc','Percentile 95% fee per transaction',
                       'Percentile 95% waiting time','Price (in USD)','Currency in the market',
                       'Market Capitalization (in USD)','Model','Liquidity','Cost','Processing time',
                       'Model Normalized','Liquidity','Cost','Processing time','Score']
Model = Model.set_index('')
for cry in ['BTC','ETH','LTC','DASH','DOGECOIN']:
    Model[cry] = np.nan

In [10]:
for cry in ['BTC','ETH','LTC']:
    Model.at['Currency in the market',cry] = Info.loc[1][cry]
    Model.at['Price (in USD)',cry] = Info.loc[2][cry]
    Model.at['Market Capitalization (in USD)',cry] = Info.loc[3][cry]

'''
#BTC Metrics
Model.at['Avg Nb transac','BTC'] = Bitcoin['Tx Count'].mean()
Model.at['Avg fee per transaction','BTC'] = Bitcoin['Avg Fee Per Tx'].mean()
Model.at['Avg reward fee per bloc','BTC'] = Bitcoin['RewardFee'].mean()
Model.at['Avg Waiting time between two blocs','BTC'] = (Bitcoin['datetime'].diff(periods=-1)).mean() 
Model.at['St dev nb transac','BTC'] = Std_nb_trans = Bitcoin['Tx Count'].std()
Model.at['St dev fee per bloc','BTC'] = Std_fee = Bitcoin['RewardFee'].std()
Model.at['St dev fee per transaction','BTC'] = Std_fee_trans = Bitcoin['Avg Fee Per Tx'].std()
Model.at['St dev waiting time between 2 blocs','BTC'] = (Bitcoin['datetime'].diff(periods=-1)).std() 
Model.at['Percentile 5% nb transac','BTC'] = Bitcoin['Tx Count'].quantile(0.05)
Model.at['Percentile 95% fee per bloc','BTC'] = Bitcoin['RewardFee'].quantile(0.95)
Model.at['Percentile 95% fee per transaction','BTC'] = Bitcoin['Avg Fee Per Tx'].quantile(0.95)
Model.at['Percentile 95% waiting time','BTC'] = (Bitcoin['datetime'].diff(periods=-1)).quantile(0.95)
'''

#LTC 
Litecoin['Avg Fee Per Tx'] = (Litecoin['fees_satoshi']/ Litecoin['transactions'])*0.00000001

Model.at['Avg Nb transac','LTC'] = Litecoin['transactions'].mean()
Model.at['Avg fee per transaction','LTC'] = Litecoin['Avg Fee Per Tx'].mean()
Model.at['Avg reward fee per bloc','LTC'] = (Litecoin['fees_satoshi'].mean())*0.00000001
Model.at['Avg Waiting time between two blocs','LTC'] = Litecoin['time_block'].mean()
Model.at['St dev nb transac','LTC'] = Litecoin['transactions'].std()
Model.at['St dev fee per bloc','LTC'] = Litecoin['fees_satoshi'].std()*0.00000001
Model.at['St dev fee per transaction','LTC'] = Litecoin['Avg Fee Per Tx'].std()
Model.at['St dev waiting time between 2 blocs','LTC'] = Litecoin['time_block'].std()
Model.at['Percentile 5% nb transac','LTC'] = Litecoin['transactions'].quantile(0.05)
Model.at['Percentile 95% fee per bloc','LTC'] = (Litecoin['fees_satoshi'].quantile(0.95))*0.00000001
Model.at['Percentile 95% fee per transaction','LTC'] = Litecoin['Avg Fee Per Tx'].quantile(0.95)
Model.at['Percentile 95% waiting time','LTC'] = Litecoin['time_block'].quantile(0.95)

#DASH
Dash['Avg Fee Per Tx'] = (Dash['fees_satoshi']/ Dash['transactions'])*0.00000001

Model.at['Avg Nb transac','DASH'] = Dash['transactions'].mean()
Model.at['Avg fee per transaction','DASH'] = Dash['Avg Fee Per Tx'].mean()
Model.at['Avg reward fee per bloc','DASH'] = (Dash['fees_satoshi'].mean())*0.00000001
Model.at['Avg Waiting time between two blocs','DASH'] = Dash['time_block'].mean()
Model.at['St dev nb transac','DASH'] = Dash['transactions'].std()
Model.at['St dev fee per bloc','DASH'] = Dash['fees_satoshi'].std()*0.00000001
Model.at['St dev fee per transaction','DASH'] = Dash['Avg Fee Per Tx'].std()
Model.at['St dev waiting time between 2 blocs','DASH'] = Dash['time_block'].std()
Model.at['Percentile 5% nb transac','DASH'] = Dash['transactions'].quantile(0.05)
Model.at['Percentile 95% fee per bloc','DASH'] = (Dash['fees_satoshi'].quantile(0.95))*0.00000001
Model.at['Percentile 95% fee per transaction','DASH'] = Dash['Avg Fee Per Tx'].quantile(0.95)
Model.at['Percentile 95% waiting time','DASH'] = Dash['time_block'].quantile(0.95)

'''
#DOGE
Dogecoin['Avg Fee Per Tx'] = (Dogecoin['fees_satoshi']/ Dogecoin['transactions'])*0.00000001

Model.at['Avg Nb transac','DOGE'] = Dogecoin['transactions'].mean()
Model.at['Avg fee per transaction','DOGE'] = Dogecoin['Avg Fee Per Tx'].mean()
Model.at['Avg reward fee per bloc','DOGE'] = (Dogecoin['fees_satoshi'].mean())*0.00000001
Model.at['Avg Waiting time between two blocs','DOGE'] = Dogecoin['time_block'].mean()
Model.at['St dev nb transac','DOGE'] = Dogecoin['transactions'].std()
Model.at['St dev fee per bloc','DOGE'] = Dogecoin['fees_satoshi'].std()*0.00000001
Model.at['St dev fee per transaction','DOGE'] = Dogecoin['Avg Fee Per Tx'].std()
Model.at['St dev waiting time between 2 blocs','DOGE'] = Dogecoin['time_block'].std()
Model.at['Percentile 5% nb transac','DOGE'] = Dogecoin['transactions'].quantile(0.05)
Model.at['Percentile 95% fee per bloc','DOGE'] = (Dogecoin['fees_satoshi'].quantile(0.95))*0.00000001
Model.at['Percentile 95% fee per transaction','DOGE'] = Dogecoin['Avg Fee Per Tx'].quantile(0.95)
Model.at['Percentile 95% waiting time','DOGE'] = Dogecoin['time_block'].quantile(0.95)
'''

#Ethereum

"\n#DOGE\nDogecoin['Avg Fee Per Tx'] = (Dogecoin['fees_satoshi']/ Dogecoin['transactions'])*0.00000001\n\nModel.at['Avg Nb transac','DOGE'] = Dogecoin['transactions'].mean()\nModel.at['Avg fee per transaction','DOGE'] = Dogecoin['Avg Fee Per Tx'].mean()\nModel.at['Avg reward fee per bloc','DOGE'] = (Dogecoin['fees_satoshi'].mean())*0.00000001\nModel.at['Avg Waiting time between two blocs','DOGE'] = Dogecoin['time_block'].mean()\nModel.at['St dev nb transac','DOGE'] = Dogecoin['transactions'].std()\nModel.at['St dev fee per bloc','DOGE'] = Dogecoin['fees_satoshi'].std()*0.00000001\nModel.at['St dev fee per transaction','DOGE'] = Dogecoin['Avg Fee Per Tx'].std()\nModel.at['St dev waiting time between 2 blocs','DOGE'] = Dogecoin['time_block'].std()\nModel.at['Percentile 5% nb transac','DOGE'] = Dogecoin['transactions'].quantile(0.05)\nModel.at['Percentile 95% fee per bloc','DOGE'] = (Dogecoin['fees_satoshi'].quantile(0.95))*0.00000001\nModel.at['Percentile 95% fee per transaction','DOGE'] = Dogecoin['Avg Fee Per Tx'].quantile(0.95)\nModel.at['Percentile 95% waiting time','DOGE'] = Dogecoin['time_block'].quantile(0.95)\n"

In [11]:
Model

,BTC,ETH,LTC,DASH,DOGECOIN
,,,,,
Avg Nb transac,NaN,NaN,58.8722,21.3333,NaN
Avg fee per transaction,NaN,NaN,0.00136233,0.000433956,NaN
Avg reward fee per bloc,NaN,NaN,0.0921158,0.010511,NaN
Avg Waiting time between two blocs,NaN,NaN,0 days 00:02:29.242424,0 days 00:03:01,NaN
St dev nb transac,NaN,NaN,51.845,10.7858,NaN
St dev fee per bloc,NaN,NaN,0.0934551,0.0104583,NaN
St dev fee per transaction,NaN,NaN,0.000813692,0.00029104,NaN
St dev waiting time between 2 blocs,NaN,NaN,0 days 00:02:21.433777,0 days 00:02:29.906637,NaN
Percentile 5% nb transac,NaN,NaN,1,10.7,NaN
Percentile 95% fee per bloc,NaN,NaN,0.255288,0.0207712,NaN
Percentile 95% fee per transaction,NaN,NaN,0.00245278,0.000720159,NaN
Percentile 95% waiting time,NaN,NaN,0 days 00:06:54.149999,0 days 00:04:36.400000,NaN
Price (in USD),1.166276e+04,4.768700e+02,102.91,NaN,NaN
Currency in the market,1.670416e+07,9.610807e+07,5.41062e+07,NaN,NaN
Market Capitalization (in USD),1.948166e+11,4.583080e+10,5.56831e+09,NaN,NaN
Model,NaN,NaN,NaN,NaN,NaN
Liquidity,NaN,NaN,NaN,NaN,NaN
Cost,NaN,NaN,NaN,NaN,NaN
Processing time,NaN,NaN,NaN,NaN,NaN
Model Normalized,NaN,NaN,NaN,NaN,NaN
Liquidity,NaN,NaN,NaN,NaN,NaN
Cost,NaN,NaN,NaN,NaN,NaN
Processing time,NaN,NaN,NaN,NaN,NaN
Score,NaN,NaN,NaN,NaN,NaN